### ISSUE TITLE
Only include species

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/unified-checklist#35]
The checklist currently contains:

taxonRank | taxa
--- | ---
GENUS | 11
SPECIES | 2399
SUBSPECIES | 101
VARIETY | 18

For a **unified** checklist, I think it makes sense to aggregate this information on **SPECIES** only, because:

- This is likely the taxonomic unit used for reporting
- This is likely the taxonomic unit used for analyses
- This makes the unified checklist easier to work with (e.g. for querying occurrences)
- This would be a documented step in the processing
- The original subspecies ranks would still be present in the original checklists, so it is traceable

This would only affect **5% of the taxa** (i.e. the non-SPECIES):

- Lumping SUBSPECIES and VARIETY under their SPECIES: this can reduce the number of taxa if more than one SUBSPECIES or VARIETY is listed for a SPECIES
- Dropping GENUS for which no species is listed on a checklist (8 taxa)

I've created a [spreadsheet of the taxa](https://docs.google.com/spreadsheets/d/1hkalx0Aivr4fyiGMkb9AiMiLviPe4rGtioBVxFNbpq0/edit?usp=sharing) that are affected.

@timadriaens @SoVDH @qgroom would you be OK with this choice?

**Comment by timadriaens** [comment]
It is probably mostly relevant for plants as is clear from the spreadsheet, where cultivars/subspecies can differ in invasiveness.

As we discussed yesterday, I am ok with that provided it is performed in the flow to the unified (so kept in the original checklist) and it is documented. Genus level PRA's are indeed not acceptable in practice. 

I checked all non-manual issues:

- no problem to lump the Trachemis scripta and Gramtemys pseudogeographica subspecies. 
- For Leiobunum, I think the genus is in because of [L. sp. A](https://www.nev.nl/pages/publicaties/eb/nummers/2011/71-5/123-129.pdf) which does occur in Belgium. As it is not yet described, it will be difficult to map it onto the backbone... 
- no problem for the spider genera, they all have a representative species

**Comment by peterdesmet** [comment]
Thanks Tim! `Ludwigia (peploides)`, `Olios (argelasius)`, `Pholcus (opilionoides)` have representative species, but not all (spider) genera. I created an issue for this in the ad hoc list: https://github.com/trias-project/ad-hoc-checklist/issues/33

**Comment by SoVDH** [comment]
Thinking about it ...
Am wondering whether it is better to aggregating variety/cultivar/subspecies to species level or rather discarding them from the unified checklist if you have a problem with keeping sub-species levels.
The reason for having sub-species levels for plants is that not all varieties behave the same way. This means if you aggregate up to species level, you mean all other potential varieties and subspecies are also present and/or established, which is sometimes wrong or sometimes unknown.
So, personally, I would either discard them for now from he unified checklist or keep them as sub-species but **NOT aggregating to species level.** 

This is a feedback from Quentin and Sonia from Zagreb

**Comment by peterdesmet** [comment]
Leaving subspecies in will be challenging, because the ideal way to search or filter for occurrences on GBIF is by `speciesKey`: that key includes all sublevels and all synonyms for a taxon, which is what we want. Example: `Reynoutria japonica`: https://www.gbif.org/species/2889173 also looks for 42 (!) synonyms and 2 varieties. It's very hard to do this otherwise.

Not aggregating them is a hard choice too, because it means they will never be considered for any analyses or emerging species, except those where the SPECIES is also listed in one of the source checklists (e.g. both `Panicum miliaceum L.` and `Panicum miliaceum subsp. miliaceum` are listed). It also throws away subspecies for animals.

I suggest we add SUBSPECIES to the list of taxa to verify, with the suggestion to lump under the species. There we can - for each taxon - decide if we want to lump them or not. By default (i.e. unverified) **they will not be included**. It then becomes a deliberate choice and we are aware of what we are throwing away.

Would that be OK?

**Comment by peterdesmet** [comment]
It basically boils down to: **how big is the net you want to use for searching occurrences**. In the result set you will still be able to see what subspecies/synonyms are included.

**Comment by qgroom** [comment]
It's a bit more than that. At least for plants we will get completely the wrong results if we model using the species data, rather than the subspecies data. 

All these have alien supspecies and common native subspecies. If we select at the species level most of the records will be for the native taxon.

Armeria maritima subsp. elongata
Equisetum hyemale
Cornus sanguinea subsp. australis
Reseda lutea subsp. vivantii 
Hippophae rhamnoides subsp. caucasica Rousi
Sedum telephium subsp. maximum
Matricaria recutita var. coronata
Phalaris arundinacea var. picta L.
Aira caryophyllea subsp. plesiantha (Jord.) K.Richt.
Pastinaca sativa subsp. urens (Req. ex Godr.) Čelak.
Lamium galeobdolon subsp. argentatum (Smejkal) J.Duvigneaud

and many more I suspect

**Comment by damianooldoni** [comment]
So, I think we solved this. The answer is: no, we need infraspecific ones in unified checklist. Issue to be closed?

**Comment by peterdesmet** [comment]
Yes, thanks for cleaning up issues @damianooldoni.
